apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - ./base

patches:
- path: extra/elastic-agent-standalone-statefulset.yaml
  target:
    kind: StatefulSet

