gcp:
  integrations_server_conf_id: "gcp.integrationsserver.n2.68x32x45"
  elasticsearch_conf_id: "gcp.es.datahot.n2.68x10x45"
  elasticsearch_deployment_template_id: "gcp-storage-optimized"
  kibana_instance_configuration_id: "gcp.kibana.n2.68x32x45"
azure:
  integrations_server_conf_id: "azure.integrationsserver.fsv2"
  elasticsearch_conf_id: "azure.es.datahot.edsv4"
  elasticsearch_deployment_template_id: "azure-storage-optimized"
  kibana_instance_configuration_id: "azure.kibana.fsv2"
aws:
  integrations_server_conf_id: "aws.integrationsserver.c5d"
  elasticsearch_conf_id: "aws.es.datahot.i3"
  elasticsearch_deployment_template_id: "aws-storage-optimized"
  kibana_instance_configuration_id: "aws.kibana.c5d"
docker:
#  integration_server_image: "docker.elastic.co/cloud-release/elastic-agent-cloud:8.16.5-3ab611f0-SNAPSHOT"
#  elasticsearch_image: "docker.elastic.co/cloud-release/elasticsearch-cloud-ess:8.16.5-3ab611f0-SNAPSHOT"
#  kibana_image: "docker.elastic.co/cloud-release/kibana-cloud:8.16.5-3ab611f0-SNAPSHOT"