{{- include "elasticagent.init" $ -}}
{{- range $presetName, $presetVal := $.Values.agent.presets }}
{{- if (eq $.Values.agent.engine "eck") -}}
{{- $agentName := include "elasticagent.preset.fullname" (list $ $presetName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $agentName }}
  namespace: {{ .namespace | default $.Release.Namespace | quote }}
  labels:
    {{- include "elasticagent.labels" $ | nindent 4 }}
    {{- with ($presetVal).labels -}}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- with ($presetVal).annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
stringData:
  agent.yml: |-
    id: {{ $agentName }}
    {{- with ($presetVal).outputs }}
    outputs:
      {{- range $outputName, $outputVal := . -}}
      {{- if ne ($outputVal).type "ESECKRef" -}}
      {{- include (printf "elasticagent.output.%s.preset.config" ($outputVal).type) (list $ $outputName $outputVal) | nindent 6 }}
      {{- end -}}
      {{- end }}
    {{- end }}
    secret_references: []
    {{- with ($presetVal).agent }}
    agent:
      {{- . | toYaml | nindent 6}}
    {{- end }}
    {{- with ($presetVal).providers }}
    providers:
      {{- . | toYaml | nindent 6 }}
    {{- end }}
    inputs:
      {{- with ($presetVal)._inputs -}}
      {{- . | toYaml | nindent 6 }}
      {{- end }}
---
{{- end -}}
{{- end }}
