apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - elastic-agent-standalone-daemonset-configmap.yaml
  - elastic-agent-standalone-daemonset.yaml
  - elastic-agent-standalone-role-binding.yaml
  - elastic-agent-standalone-role.yaml
  - elastic-agent-standalone-service-account.yaml
  