inputs:
    - name: filestream-checkpoint
      id: filestream-checkpoint-${kubernetes.hints.container_id}
      type: filestream
      use_output: default
      streams:
        - condition: ${kubernetes.hints.checkpoint.firewall.enabled} == true or ${kubernetes.hints.checkpoint.enabled} == true
          id: filestream-checkpoint-firewall-${kubernetes.hints.container_id}
          data_stream:
            dataset: checkpoint.firewall
            type: logs
          exclude_files:
            - .gz$
          file_identity:
            fingerprint: null
          parsers:
            - container:
                format: auto
                stream: ${kubernetes.hints.checkpoint.firewall.stream|'all'}
          paths:
            - /var/log/containers/*${kubernetes.hints.container_id}.log
          processors:
            - add_locale: null
            - add_fields:
                fields:
                    internal_zones:
                        - trust
                target: _temp_
            - add_fields:
                fields:
                    external_zones:
                        - untrust
                target: _temp_
          prospector:
            scanner:
                fingerprint:
                    enabled: true
                symlinks: true
          tags:
            - forwarded
      data_stream.namespace: default
    - name: tcp-checkpoint
      id: tcp-checkpoint-${kubernetes.hints.container_id}
      type: tcp
      use_output: default
      streams:
        - condition: ${kubernetes.hints.checkpoint.firewall.enabled} == true or ${kubernetes.hints.checkpoint.enabled} == true
          data_stream:
            dataset: checkpoint.firewall
            type: logs
          host: localhost:9001
          processors:
            - add_locale: null
          tags:
            - forwarded
      data_stream.namespace: default
    - name: udp-checkpoint
      id: udp-checkpoint-${kubernetes.hints.container_id}
      type: udp
      use_output: default
      streams:
        - condition: ${kubernetes.hints.checkpoint.firewall.enabled} == true or ${kubernetes.hints.checkpoint.enabled} == true
          data_stream:
            dataset: checkpoint.firewall
            type: logs
          host: localhost:9001
          processors:
            - add_locale: null
          tags:
            - forwarded
      data_stream.namespace: default
