inputs:
    - name: journald-iptables
      type: journald
      use_output: default
      streams:
        - condition: ${kubernetes.hints.iptables.log.enabled} == true or ${kubernetes.hints.iptables.enabled} == true
          data_stream:
            dataset: iptables.log
            type: logs
          include_matches:
            - _TRANSPORT=kernel
          tags:
            - iptables-log
      data_stream.namespace: default
    - name: udp-iptables
      type: udp
      use_output: default
      streams:
        - condition: ${kubernetes.hints.iptables.log.enabled} == true or ${kubernetes.hints.iptables.enabled} == true
          data_stream:
            dataset: iptables.log
            type: logs
          host: localhost:9001
          processors:
            - add_locale: null
          tags:
            - iptables-log
            - forwarded
      data_stream.namespace: default
    - name: filestream-iptables
      type: filestream
      use_output: default
      streams:
        - condition: ${kubernetes.hints.iptables.log.enabled} == true and ${kubernetes.hints.iptables.enabled} == true
          data_stream:
            dataset: iptables.log
            type: logs
          exclude_files:
            - .gz$
          parsers:
            - container:
                format: auto
                stream: ${kubernetes.hints.iptables.log.stream|'all'}
          paths:
            - /var/log/containers/*${kubernetes.hints.container_id}.log
          processors:
            - add_locale: null
          prospector:
            scanner:
                symlinks: true
          tags:
            - iptables-log
            - forwarded
      data_stream.namespace: default
