inputs:
    - name: filestream-kafka
      type: filestream
      use_output: default
      streams:
        - condition: ${kubernetes.hints.kafka.log.enabled} == true or ${kubernetes.hints.kafka.enabled} == true
          data_stream:
            dataset: kafka.log
            type: logs
          exclude_files:
            - .gz$
          multiline:
            match: after
            negate: true
            pattern: ^\[
          parsers:
            - container:
                format: auto
                stream: ${kubernetes.hints.kafka.log.stream|'all'}
          paths:
            - /opt/kafka*/var/log/containers/*${kubernetes.hints.container_id}.log
          processors:
            - add_locale: null
          prospector:
            scanner:
                symlinks: true
          tags:
            - kafka-log
      data_stream.namespace: default
    - name: kafka/metrics-kafka
      type: kafka/metrics
      use_output: default
      streams:
        - condition: ${kubernetes.hints.kafka.broker.enabled} == true or ${kubernetes.hints.kafka.enabled} == true
          data_stream:
            dataset: kafka.broker
            type: metrics
          hosts:
            - localhost:8778
          metricsets:
            - broker
          period: ${kubernetes.hints.kafka.broker.period|kubernetes.hints.kafka.period|'10s'}
        - condition: ${kubernetes.hints.kafka.consumergroup.enabled} == true or ${kubernetes.hints.kafka.enabled} == true
          data_stream:
            dataset: kafka.consumergroup
            type: metrics
          hosts:
            - ${kubernetes.hints.kafka.consumergroup.host|kubernetes.hints.kafka.host|'localhost:9092'}
          metricsets:
            - consumergroup
          period: ${kubernetes.hints.kafka.consumergroup.period|kubernetes.hints.kafka.period|'10s'}
        - condition: ${kubernetes.hints.kafka.partition.enabled} == true or ${kubernetes.hints.kafka.enabled} == true
          data_stream:
            dataset: kafka.partition
            type: metrics
          hosts:
            - ${kubernetes.hints.kafka.partition.host|kubernetes.hints.kafka.host|'localhost:9092'}
          metricsets:
            - partition
          period: ${kubernetes.hints.kafka.partition.period|kubernetes.hints.kafka.period|'10s'}
      data_stream.namespace: default
