inputs:
    - name: filestream-nats
      type: filestream
      use_output: default
      streams:
        - condition: ${kubernetes.hints.nats.log.enabled} == true or ${kubernetes.hints.nats.enabled} == true
          data_stream:
            dataset: nats.log
            type: logs
          exclude_files:
            - .gz$
          parsers:
            - container:
                format: auto
                stream: ${kubernetes.hints.nats.log.stream|all}
          paths:
            - /var/log/containers/*${kubernetes.hints.container_id}.log
          processors: ${kubernetes.hints.nats.log.processors}
          prospector:
            scanner:
                symlinks: true
          tags:
            - nats-log
      data_stream.namespace: default
    - name: nats/metrics-nats
      type: nats/metrics
      use_output: default
      streams:
        - condition: ${kubernetes.hints.nats.connection.enabled} == true and ${kubernetes.hints.nats.enabled} == true
          data_stream:
            dataset: nats.connection
            type: metrics
          hosts:
            - ${kubernetes.hints.nats.connection.host|localhost:8222}
          metricsets:
            - connection
          period: ${kubernetes.hints.nats.connection.period|10s}
          processors: ${kubernetes.hints.nats.connection.processors}
        - condition: ${kubernetes.hints.nats.connections.enabled} == true or ${kubernetes.hints.nats.enabled} == true
          data_stream:
            dataset: nats.connections
            type: metrics
          hosts:
            - ${kubernetes.hints.nats.connections.host|localhost:8222}
          metricsets:
            - connections
          period: ${kubernetes.hints.nats.connections.period|10s}
          processors: ${kubernetes.hints.nats.connections.processors}
        - condition: ${kubernetes.hints.nats.route.enabled} == true and ${kubernetes.hints.nats.enabled} == true
          data_stream:
            dataset: nats.route
            type: metrics
          hosts:
            - ${kubernetes.hints.nats.route.host|localhost:8222}
          metricsets:
            - route
          period: ${kubernetes.hints.nats.route.period|10s}
          processors: ${kubernetes.hints.nats.route.processors}
        - condition: ${kubernetes.hints.nats.routes.enabled} == true or ${kubernetes.hints.nats.enabled} == true
          data_stream:
            dataset: nats.routes
            type: metrics
          hosts:
            - ${kubernetes.hints.nats.routes.host|localhost:8222}
          metricsets:
            - routes
          period: ${kubernetes.hints.nats.routes.period|10s}
          processors: ${kubernetes.hints.nats.routes.processors}
        - condition: ${kubernetes.hints.nats.stats.enabled} == true or ${kubernetes.hints.nats.enabled} == true
          data_stream:
            dataset: nats.stats
            type: metrics
          hosts:
            - ${kubernetes.hints.nats.stats.host|localhost:8222}
          metricsets:
            - stats
          period: ${kubernetes.hints.nats.stats.period|10s}
          processors: ${kubernetes.hints.nats.stats.processors}
        - condition: ${kubernetes.hints.nats.subscriptions.enabled} == true or ${kubernetes.hints.nats.enabled} == true
          data_stream:
            dataset: nats.subscriptions
            type: metrics
          hosts:
            - ${kubernetes.hints.nats.subscriptions.host|localhost:8222}
          metricsets:
            - subscriptions
          period: ${kubernetes.hints.nats.subscriptions.period|10s}
          processors: ${kubernetes.hints.nats.subscriptions.processors}
      data_stream.namespace: default
