inputs:
    - name: filestream-osquery_manager
      type: filestream
      use_output: default
      streams:
        - condition: ${kubernetes.hints.osquery_manager.container_logs.enabled} == true
          data_stream:
            dataset: kubernetes.container_logs
            type: logs
          exclude_files: []
          exclude_lines: []
          parsers:
            - container:
                format: auto
                stream: all
          paths:
            - /var/log/containers/*${kubernetes.hints.container_id}.log
          prospector:
            scanner:
                symlinks: true
          tags: []
      data_stream.namespace: default
    - name: osquery-osquery_manager
      type: osquery
      use_output: default
      streams:
        - condition: ${kubernetes.hints.osquery_manager.result.enabled} == true or ${kubernetes.hints.osquery_manager.enabled} == true
          data_stream:
            dataset: osquery_manager.result
            type: logs
          id: null
          query: null
      data_stream.namespace: default
