inputs:
    - name: filestream-osquery
      type: filestream
      use_output: default
      streams:
        - condition: ${kubernetes.hints.osquery.result.enabled} == true or ${kubernetes.hints.osquery.enabled} == true
          data_stream:
            dataset: osquery.result
            type: logs
          exclude_files:
            - .gz$
          parsers:
            - container:
                format: auto
                stream: ${kubernetes.hints.osquery.result.stream|all}
          paths:
            - /var/log/containers/*${kubernetes.hints.container_id}.log
          processors: ${kubernetes.hints.osquery.result.processors}
          prospector:
            scanner:
                symlinks: true
          tags:
            - osquery
      data_stream.namespace: default
