inputs:
    - name: filestream-rabbitmq
      type: filestream
      use_output: default
      streams:
        - condition: ${kubernetes.hints.rabbitmq.log.enabled} == true or ${kubernetes.hints.rabbitmq.enabled} == true
          data_stream:
            dataset: rabbitmq.log
            type: logs
          exclude_files:
            - .gz$
          multiline:
            match: after
            negate: true
            pattern: '[0-9]{4}-[0-9]{2}-[0-9]{2}'
          parsers:
            - container:
                format: auto
                stream: ${kubernetes.hints.rabbitmq.log.stream|all}
          paths:
            - /var/log/containers/*${kubernetes.hints.container_id}.log
          processors:
            - add_locale: null
          prospector:
            scanner:
                symlinks: true
          tags:
            - forwarded
      data_stream.namespace: default
    - name: rabbitmq/metrics-rabbitmq
      type: rabbitmq/metrics
      use_output: default
      streams:
        - condition: ${kubernetes.hints.rabbitmq.connection.enabled} == true or ${kubernetes.hints.rabbitmq.enabled} == true
          data_stream:
            dataset: rabbitmq.connection
            type: metrics
          hosts:
            - ${kubernetes.hints.rabbitmq.connection.host|localhost:15672}
          metricsets:
            - connection
          password: ${kubernetes.hints.rabbitmq.connection.password|}
          period: ${kubernetes.hints.rabbitmq.connection.period|10s}
          processors: ${kubernetes.hints.rabbitmq.connection.processors}
          username: ${kubernetes.hints.rabbitmq.connection.username|}
        - condition: ${kubernetes.hints.rabbitmq.exchange.enabled} == true or ${kubernetes.hints.rabbitmq.enabled} == true
          data_stream:
            dataset: rabbitmq.exchange
            type: metrics
          hosts:
            - ${kubernetes.hints.rabbitmq.exchange.host|localhost:15672}
          metricsets:
            - exchange
          password: ${kubernetes.hints.rabbitmq.exchange.password|}
          period: ${kubernetes.hints.rabbitmq.exchange.period|10s}
          processors: ${kubernetes.hints.rabbitmq.exchange.processors}
          username: ${kubernetes.hints.rabbitmq.exchange.username|}
        - condition: ${kubernetes.hints.rabbitmq.node.enabled} == true or ${kubernetes.hints.rabbitmq.enabled} == true
          data_stream:
            dataset: rabbitmq.node
            type: metrics
          hosts:
            - ${kubernetes.hints.rabbitmq.node.host|localhost:15672}
          metricsets:
            - node
          node.collect: node
          password: ${kubernetes.hints.rabbitmq.node.password|}
          period: ${kubernetes.hints.rabbitmq.node.period|10s}
          processors: ${kubernetes.hints.rabbitmq.node.processors}
          username: ${kubernetes.hints.rabbitmq.node.username|}
        - condition: ${kubernetes.hints.rabbitmq.queue.enabled} == true or ${kubernetes.hints.rabbitmq.enabled} == true
          data_stream:
            dataset: rabbitmq.queue
            type: metrics
          hosts:
            - ${kubernetes.hints.rabbitmq.queue.host|localhost:15672}
          metricsets:
            - queue
          password: ${kubernetes.hints.rabbitmq.queue.password|}
          period: ${kubernetes.hints.rabbitmq.queue.period|10s}
          processors: ${kubernetes.hints.rabbitmq.queue.processors}
          username: ${kubernetes.hints.rabbitmq.queue.username|}
      data_stream.namespace: default
