# Turn off everything except the AutoOps preset
kubernetes:
  enabled: false
kube-state-metrics:
  enabled: false

autoOps:
  enabled: true
  autoops_token: "REPLACE_ME_TOKEN"
  autoops_otel_url: "https://otel.example.com:4318"
  autoops_temp_resource_id: "REPLACE_ME_RESOURCE_ID"
  es_api_key: "REPLACE_ME_API_KEY"
  elastic_cloud_connected_mode_api_key: "CCM-API-KEY"
  elastic_cloud_connected_mode_api_url: "CCM-API-URL"
  autoops_es_url: "https://ccm-test-eu-west-1.es.us-east-2.aws.elastic-cloud.com"
