apiVersion: v2
name: elastic-agent
description: Elastic-Agent Helm Chart
kubeVersion: ">= 1.27.0-0"
type: application
appVersion: 8.18.0
version: 8.18.0-beta
dependencies:
  - name: kube-state-metrics
    version: "5.28.0"
    repository: https://prometheus-community.github.io/helm-charts
    condition: kube-state-metrics.enabled
