apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
  - elastic-agent-managed-daemonset.yaml
  - elastic-agent-managed-role-binding.yaml
  - elastic-agent-managed-role.yaml
  - elastic-agent-managed-service-account.yaml